-- Faraj League — all pending database changes, in order.
-- Run once in Supabase Dashboard → SQL Editor. Safe to re-run.
-- Generated from: migrations 010, 011 + seed_fall2026_players.sql + sponsors_fall2026_cleanup.sql

-- ============================================================
-- 1. Migration 010 — one active season at a time
-- ============================================================
-- Faraj League: multi-season support
-- Run after 009_forfeit_team_id.sql

-- Collapse any pre-existing duplicates down to the newest current season so the
-- unique index below can be created.
UPDATE seasons SET is_current = false
WHERE is_current
  AND id <> (SELECT id FROM seasons WHERE is_current ORDER BY created_at DESC LIMIT 1);

-- At most one season may be current at a time. The public site loads the current
-- season by default, so a second one would make that choice non-deterministic.
CREATE UNIQUE INDEX IF NOT EXISTS seasons_one_current_idx
  ON seasons (is_current) WHERE is_current;

-- Season lookups by slug happen on every page load.
CREATE INDEX IF NOT EXISTS idx_seasons_created_at ON seasons (created_at DESC);

-- ============================================================
-- 2. Migration 011 — per-season team logos
-- ============================================================
-- Faraj League: per-season team logos
-- Run after 010_seasons_multi.sql

-- Logos used to be resolved by matching the team name against files committed
-- in images/teams/, which meant renaming a team silently changed (or lost) its
-- logo, and two seasons could never show different logos for the same club.
-- teams rows are already per-season, so putting the logo here scopes it too.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS logo_url TEXT;

-- Logos are cropped into a circle, so each needs its own zoom. NULL means the
-- renderer's default. Kept alongside logo_url because the two are only useful
-- together.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS logo_scale NUMERIC;

ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_logo_scale_range;
ALTER TABLE teams ADD CONSTRAINT teams_logo_scale_range
  CHECK (logo_scale IS NULL OR (logo_scale > 0 AND logo_scale <= 10));

-- ============================================================
-- 3. Fall 2026 roster — 42 players
-- ============================================================
-- Fall 2026 roster — 42 players
-- Source: Season 2 · Fall draft board
-- Generated by scripts/import-roster.js — edit the JSON, not this file.
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.
--
-- The CROSS JOIN against seasons is what scopes this to one season: if no row
-- matches the slug, zero players are inserted rather than landing anywhere else.

INSERT INTO players (season_id, name)
SELECT season.id, incoming.name
FROM seasons AS season
CROSS JOIN (VALUES
    ('Kumail Naqvi'::TEXT),
    ('AliReza Mirza'),
    ('Yousif Albiaag'),
    ('Mohammed Rushayd Mukhi'),
    ('Aun Ali'),
    ('Yusuf Zaidi'),
    ('Dayyem Raza'),
    ('Murtuza Hussain'),
    ('Mohsinhasan Hemani'),
    ('Hanny Ali'),
    ('Mohammad Ali'),
    ('Amir Golabbakhsh'),
    ('Ali Numa Raza'),
    ('Murtaza Jaffry'),
    ('Humza Zaidi'),
    ('Humza Hussain'),
    ('Raza Saiyed'),
    ('Ali Zaidi'),
    ('Zaki Rizvi'),
    ('Raamiz Jafri'),
    ('Kumayl Sheikh'),
    ('Abbas Zaidi'),
    ('Zaamin Mehdi'),
    ('Ghulam Asghar Ali'),
    ('Alihussain Taqvi'),
    ('Hani Zaidi'),
    ('Zachariah Kader'),
    ('Ahmed Syed'),
    ('Meesam Naqvi'),
    ('Mohammad Hasnain'),
    ('Mohammad Syed'),
    ('Muhammad Rizvi'),
    ('Hyder Radhi'),
    ('Rayan Jafri'),
    ('Imran Kader'),
    ('Ali Abidi'),
    ('Ali Rizvi'),
    ('Khizr Aun'),
    ('Mohammad Zaidi'),
    ('Omeed Tafreshi'),
    ('Muhammad Zaidi'),
    ('Sohail Dhanji')
) AS incoming (name)
WHERE season.slug = 'fall2026'
  AND NOT EXISTS (
    SELECT 1 FROM players existing
    WHERE existing.season_id = season.id
      AND lower(existing.name) = lower(incoming.name)
  );


-- ============================================================
-- 4. Sponsors — clear Fall 2026, pin Spring 2026's into its own rows
-- ============================================================
-- Remove the conference/title sponsors from Fall 2026, and pin Spring 2026's
-- sponsors into its own data so it is unaffected.
--
-- Background: the site used to fall back to hard-coded sponsor names and logos
-- whenever a season had none, which is why clearing them in admin appeared to
-- do nothing. Those fallbacks are gone. Spring 2026 relied on them, so its
-- values are written into its own sponsor rows here — after this it renders
-- from data exactly as it did before.
--
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.

-- 1. Spring 2026 keeps its branding, stored properly.
--    Fills a missing row, and fills a blank column on an existing row. Never
--    overwrites a value that is already set.
INSERT INTO sponsors (season_id, type, name, logo_url)
SELECT s.id, v.type, v.name, v.logo_url
FROM seasons s
CROSS JOIN (VALUES
  ('title'::TEXT,            'Zabiha Family Ranch'::TEXT, 'images/zabiha-logo.png'::TEXT),
  ('conference_mecca',       'TOYOMOTORS',                'images/toyomotors-logo.png'),
  ('conference_medina',      'Xtreme Wellness',           'images/wellness-logo.png')
) AS v (type, name, logo_url)
WHERE s.slug = 'spring2026'
  AND NOT EXISTS (
    SELECT 1 FROM sponsors x WHERE x.season_id = s.id AND x.type = v.type
  );

UPDATE sponsors sp
SET name = COALESCE(NULLIF(sp.name, ''), v.name),
    logo_url = COALESCE(NULLIF(sp.logo_url, ''), v.logo_url)
FROM seasons s,
  (VALUES
    ('title'::TEXT,       'Zabiha Family Ranch'::TEXT, 'images/zabiha-logo.png'::TEXT),
    ('conference_mecca',  'TOYOMOTORS',                'images/toyomotors-logo.png'),
    ('conference_medina', 'Xtreme Wellness',           'images/wellness-logo.png')
  ) AS v (type, name, logo_url)
WHERE sp.season_id = s.id
  AND s.slug = 'spring2026'
  AND sp.type = v.type
  AND (sp.name IS NULL OR sp.name = '' OR sp.logo_url IS NULL OR sp.logo_url = '');

-- 2. Fall 2026 loses its sponsor rows entirely.
DELETE FROM sponsors
WHERE season_id = (SELECT id FROM seasons WHERE slug = 'fall2026');

-- 3. ...and any community-partner blocks carried over with them.
DELETE FROM content_blocks
WHERE season_id = (SELECT id FROM seasons WHERE slug = 'fall2026')
  AND key LIKE 'sponsor_community_%';


-- ============================================================
-- Confirmation: expect 42 Fall players, 3 Spring sponsors, 0 Fall sponsors
-- ============================================================
SELECT s.slug,
       (SELECT count(*) FROM players  p WHERE p.season_id  = s.id) AS players,
       (SELECT count(*) FROM sponsors sp WHERE sp.season_id = s.id) AS sponsors,
       s.is_current
FROM seasons s
ORDER BY s.created_at DESC;
