-- Faraj League — all pending database changes, in order.
-- Run once in Supabase Dashboard → SQL Editor. Safe to re-run.
-- Generated from: migrations 010, 011, 012 + seed_fall2026_players.sql + sponsors_fall2026_cleanup.sql

-- ============================================================
-- 1. Migration 010 — one active season at a time
-- ============================================================
-- Faraj League: multi-season support
-- Run after 009_forfeit_team_id.sql

-- Collapse any pre-existing duplicates down to the newest current season so the
-- unique index below can be created.
UPDATE seasons SET is_current = false
WHERE is_current
  AND id <> (SELECT id FROM seasons WHERE is_current ORDER BY created_at DESC LIMIT 1);

-- At most one season may be current at a time. The public site loads the current
-- season by default, so a second one would make that choice non-deterministic.
CREATE UNIQUE INDEX IF NOT EXISTS seasons_one_current_idx
  ON seasons (is_current) WHERE is_current;

-- Season lookups by slug happen on every page load.
CREATE INDEX IF NOT EXISTS idx_seasons_created_at ON seasons (created_at DESC);

-- ============================================================
-- 2. Migration 011 — per-season team logos
-- ============================================================
-- Faraj League: per-season team logos
-- Run after 010_seasons_multi.sql

-- Logos used to be resolved by matching the team name against files committed
-- in images/teams/, which meant renaming a team silently changed (or lost) its
-- logo, and two seasons could never show different logos for the same club.
-- teams rows are already per-season, so putting the logo here scopes it too.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS logo_url TEXT;

-- Logos are cropped into a circle, so each needs its own zoom. NULL means the
-- renderer's default. Kept alongside logo_url because the two are only useful
-- together.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS logo_scale NUMERIC;

ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_logo_scale_range;
ALTER TABLE teams ADD CONSTRAINT teams_logo_scale_range
  CHECK (logo_scale IS NULL OR (logo_scale > 0 AND logo_scale <= 10));

-- ============================================================
-- 3. Migration 012 — live game status and clock
-- ============================================================
-- Faraj League: live game status and clock
-- Run after 011_team_logo.sql

-- Before this, a game showed a winner the moment it had any score — so a game
-- in progress read as finished as soon as one team led. These columns let the
-- public site tell "in progress" from "final".
--
-- status: NULL for everything recorded before this migration. A NULL status on
-- a game that has scores is treated as final, so past seasons are unaffected.
ALTER TABLE games ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS period INT;

-- The clock is stored as "this many seconds remained, as of this instant".
-- Viewers extrapolate from clock_updated_at while clock_running is true, so a
-- running clock ticks smoothly on a phone without the tracker writing a row
-- every second.
ALTER TABLE games ADD COLUMN IF NOT EXISTS clock_seconds INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS clock_running BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE games ADD COLUMN IF NOT EXISTS clock_updated_at TIMESTAMPTZ;

ALTER TABLE games DROP CONSTRAINT IF EXISTS games_status_values;
ALTER TABLE games ADD CONSTRAINT games_status_values
  CHECK (status IS NULL OR status IN ('scheduled', 'live', 'halftime', 'final'));

-- ============================================================
-- 4. Fall 2026 roster — 42 players
-- ============================================================
-- Fall 2026 roster — 42 players
-- Source: Season 2 · Fall draft board
-- Generated by scripts/import-roster.js — edit the JSON, not this file.
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.
--
-- The CROSS JOIN against seasons is what scopes this to one season: if no row
-- matches the slug, zero players are inserted rather than landing anywhere else.

INSERT INTO players (season_id, name)
SELECT season.id, incoming.name
FROM seasons AS season
CROSS JOIN (VALUES
    ('Kumail Naqvi'::TEXT),
    ('AliReza Mirza'),
    ('Yousif Albiaag'),
    ('Mohammed Rushayd Mukhi'),
    ('Aun Ali'),
    ('Yusuf Zaidi'),
    ('Dayyem Raza'),
    ('Murtuza Hussain'),
    ('Mohsinhasan Hemani'),
    ('Hanny Ali'),
    ('Mohammad Ali'),
    ('Amir Golabbakhsh'),
    ('Ali Numa Raza'),
    ('Murtaza Jaffry'),
    ('Humza Zaidi'),
    ('Humza Hussain'),
    ('Raza Saiyed'),
    ('Ali Zaidi'),
    ('Zaki Rizvi'),
    ('Raamiz Jafri'),
    ('Kumayl Sheikh'),
    ('Abbas Zaidi'),
    ('Zaamin Mehdi'),
    ('Ghulam Asghar Ali'),
    ('Alihussain Taqvi'),
    ('Hani Zaidi'),
    ('Zachariah Kader'),
    ('Ahmed Syed'),
    ('Meesam Naqvi'),
    ('Mohammad Hasnain'),
    ('Mohammad Syed'),
    ('Muhammad Rizvi'),
    ('Hyder Radhi'),
    ('Rayan Jafri'),
    ('Imran Kader'),
    ('Ali Abidi'),
    ('Ali Rizvi'),
    ('Khizr Aun'),
    ('Mohammad Zaidi'),
    ('Omeed Tafreshi'),
    ('Muhammad Zaidi'),
    ('Sohail Dhanji')
) AS incoming (name)
WHERE season.slug = 'fall2026'
  AND NOT EXISTS (
    SELECT 1 FROM players existing
    WHERE existing.season_id = season.id
      AND lower(existing.name) = lower(incoming.name)
  );


-- ============================================================
-- 5. Sponsors — Fall keeps its title sponsor, loses the conference ones;
--    Spring's are pinned into its own rows
-- ============================================================
-- Remove the CONFERENCE sponsors from Fall 2026 (keeping its title sponsor),
-- and pin Spring 2026's sponsors into its own data so it is unaffected.
--
-- Background: the site used to fall back to hard-coded sponsor names and logos
-- whenever a season had none, which is why clearing them in admin appeared to
-- do nothing. Those fallbacks are gone. Spring 2026 relied on them, so its
-- values are written into its own sponsor rows here — after this it renders
-- from data exactly as it did before.
--
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.

-- 1. Spring 2026 keeps its branding, stored properly.
--    Fills a missing row, and fills a blank column on an existing row. Never
--    overwrites a value that is already set.
INSERT INTO sponsors (season_id, type, name, logo_url)
SELECT s.id, v.type, v.name, v.logo_url
FROM seasons s
CROSS JOIN (VALUES
  ('title'::TEXT,            'Zabiha Family Ranch'::TEXT, 'images/zabiha-logo.png'::TEXT),
  ('conference_mecca',       'TOYOMOTORS',                'images/toyomotors-logo.png'),
  ('conference_medina',      'Xtreme Wellness',           'images/wellness-logo.png')
) AS v (type, name, logo_url)
WHERE s.slug = 'spring2026'
  AND NOT EXISTS (
    SELECT 1 FROM sponsors x WHERE x.season_id = s.id AND x.type = v.type
  );

UPDATE sponsors sp
SET name = COALESCE(NULLIF(sp.name, ''), v.name),
    logo_url = COALESCE(NULLIF(sp.logo_url, ''), v.logo_url)
FROM seasons s,
  (VALUES
    ('title'::TEXT,       'Zabiha Family Ranch'::TEXT, 'images/zabiha-logo.png'::TEXT),
    ('conference_mecca',  'TOYOMOTORS',                'images/toyomotors-logo.png'),
    ('conference_medina', 'Xtreme Wellness',           'images/wellness-logo.png')
  ) AS v (type, name, logo_url)
WHERE sp.season_id = s.id
  AND s.slug = 'spring2026'
  AND sp.type = v.type
  AND (sp.name IS NULL OR sp.name = '' OR sp.logo_url IS NULL OR sp.logo_url = '');

-- 2. Fall 2026 keeps its title sponsor but loses the conference ones.
--    The conference sponsors are where the Akhlaq award label and the
--    conference headings get their branding.
DELETE FROM sponsors
WHERE season_id = (SELECT id FROM seasons WHERE slug = 'fall2026')
  AND type IN ('conference_mecca', 'conference_medina');

-- 3. ...and any community-partner blocks carried over with them.
DELETE FROM content_blocks
WHERE season_id = (SELECT id FROM seasons WHERE slug = 'fall2026')
  AND key LIKE 'sponsor_community_%';

-- 4. Make sure Fall still has a title sponsor, matching Spring's. Reaches this
--    state from any starting point, including an earlier over-broad cleanup
--    that removed it.
INSERT INTO sponsors (season_id, type, name, logo_url, label)
SELECT f.id, 'title',
       COALESCE(sp.name, 'Zabiha Family Ranch'),
       COALESCE(sp.logo_url, 'images/zabiha-logo.png'),
       sp.label
FROM seasons f
LEFT JOIN seasons s ON s.slug = 'spring2026'
LEFT JOIN sponsors sp ON sp.season_id = s.id AND sp.type = 'title'
WHERE f.slug = 'fall2026'
  AND NOT EXISTS (
    SELECT 1 FROM sponsors x WHERE x.season_id = f.id AND x.type = 'title'
  );

UPDATE sponsors t
SET name = COALESCE(NULLIF(t.name, ''), sp.name, 'Zabiha Family Ranch'),
    logo_url = COALESCE(NULLIF(t.logo_url, ''), sp.logo_url, 'images/zabiha-logo.png')
FROM seasons f
LEFT JOIN seasons s ON s.slug = 'spring2026'
LEFT JOIN sponsors sp ON sp.season_id = s.id AND sp.type = 'title'
WHERE t.season_id = f.id
  AND f.slug = 'fall2026'
  AND t.type = 'title'
  AND (t.name IS NULL OR t.name = '' OR t.logo_url IS NULL OR t.logo_url = '');


-- ============================================================
-- Confirmation: 42 Fall players, 3 Spring sponsors, 1 Fall sponsor (title)
-- ============================================================
SELECT s.slug,
       (SELECT count(*) FROM players  p WHERE p.season_id  = s.id) AS players,
       (SELECT count(*) FROM sponsors sp WHERE sp.season_id = s.id) AS sponsors,
       s.is_current
FROM seasons s
ORDER BY s.created_at DESC;
