-- Fall 2026 roster — 42 players
-- Source: Season 2 · Fall draft board
-- Generated by scripts/import-roster.js — edit the JSON, not this file.
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.
--
-- The CROSS JOIN against seasons is what scopes this to one season: if no row
-- matches the slug, zero players are inserted rather than landing anywhere else.

INSERT INTO players (season_id, name)
SELECT season.id, incoming.name
FROM seasons AS season
CROSS JOIN (VALUES
    ('Kumail Naqvi'::TEXT),
    ('AliReza Mirza'),
    ('Yousif Albiaag'),
    ('Mohammed Rushayd Mukhi'),
    ('Aun Ali'),
    ('Yusuf Zaidi'),
    ('Dayyem Raza'),
    ('Murtuza Hussain'),
    ('Mohsinhasan Hemani'),
    ('Hanny Ali'),
    ('Mohammad Ali'),
    ('Amir Golabbakhsh'),
    ('Ali Numa Raza'),
    ('Murtaza Jaffry'),
    ('Humza Zaidi'),
    ('Humza Hussain'),
    ('Raza Saiyed'),
    ('Ali Zaidi'),
    ('Zaki Rizvi'),
    ('Raamiz Jafri'),
    ('Kumayl Sheikh'),
    ('Abbas Zaidi'),
    ('Zaamin Mehdi'),
    ('Ghulam Asghar Ali'),
    ('Alihussain Taqvi'),
    ('Hani Zaidi'),
    ('Zachariah Kader'),
    ('Ahmed Syed'),
    ('Meesam Naqvi'),
    ('Mohammad Hasnain'),
    ('Mohammad Syed'),
    ('Muhammad Rizvi'),
    ('Hyder Radhi'),
    ('Rayan Jafri'),
    ('Imran Kader'),
    ('Ali Abidi'),
    ('Ali Rizvi'),
    ('Khizr Aun'),
    ('Mohammad Zaidi'),
    ('Omeed Tafreshi'),
    ('Muhammad Zaidi'),
    ('Sohail Dhanji')
) AS incoming (name)
WHERE season.slug = 'fall2026'
  AND NOT EXISTS (
    SELECT 1 FROM players existing
    WHERE existing.season_id = season.id
      AND lower(existing.name) = lower(incoming.name)
  );

-- Confirmation — expect 42. A 0 here means the season does not exist yet.
SELECT count(*) AS players_in_fall2026
FROM players p
JOIN seasons s ON s.id = p.season_id
WHERE s.slug = 'fall2026';
