/**
 * Import a season roster (player names) from a JSON file in scripts/rosters/.
 *
 *   node scripts/import-roster.js scripts/rosters/fall2026.json
 *   node scripts/import-roster.js scripts/rosters/fall2026.json --sql > roster.sql
 *
 * Default mode writes to Supabase and needs SUPABASE_SERVICE_ROLE_KEY in .env
 * (the anon key cannot insert — RLS only allows public read).
 * `--sql` needs no credentials: it prints SQL to paste into the Supabase
 * Dashboard → SQL Editor, which is the route the rest of this repo documents.
 *
 * Idempotent either way: a player already in that season (same name, ignoring
 * case) is skipped, so re-running never creates duplicates. Players are scoped
 * to the season the JSON names; no other season is touched.
 */
import { readFileSync } from 'node:fs';

function parseArgs(argv) {
  const args = argv.slice(2);
  const sqlOnly = args.includes('--sql');
  const rosterPath = args.find(a => !a.startsWith('--'));
  if (!rosterPath) {
    console.error('Usage: node scripts/import-roster.js <roster.json> [--sql]');
    process.exit(1);
  }
  return { rosterPath, sqlOnly };
}

/**
 * Validate a roster file up front so a bad row fails before anything is written.
 * @returns {string[]} human-readable problems; empty when the file is usable
 */
export function validateRoster(roster) {
  const errors = [];
  if (!roster?.season?.slug) errors.push('season.slug is required');
  if (!Array.isArray(roster?.players) || roster.players.length === 0) {
    errors.push('players[] is required and must not be empty');
    return errors;
  }
  const seen = new Set();
  roster.players.forEach((name, i) => {
    if (typeof name !== 'string' || !name.trim()) {
      errors.push(`players[${i}]: expected a non-empty name`);
      return;
    }
    const key = name.trim().toLowerCase();
    if (seen.has(key)) errors.push(`players[${i}]: duplicate name "${name}" in this file`);
    seen.add(key);
  });
  return errors;
}

/** Single-quote escape for SQL string literals. */
const q = (v) => `'${String(v).replace(/'/g, "''")}'`;

/**
 * Emit idempotent INSERTs scoped to one season, for the Dashboard SQL Editor.
 * @returns {string} SQL
 */
export function toSql(roster) {
  const slug = roster.season.slug;
  // Casting the first row anchors the column type for the whole VALUES list.
  const rows = roster.players
    .map((name, i) => `    (${q(name.trim())}${i === 0 ? '::TEXT' : ''})`)
    .join(',\n');

  return `-- ${roster.season.label || slug} roster — ${roster.players.length} players
-- Source: ${roster.source || `scripts/rosters/${slug}.json`}
-- Generated by scripts/import-roster.js — edit the JSON, not this file.
-- Run in Supabase Dashboard → SQL Editor. Safe to run more than once.
--
-- The CROSS JOIN against seasons is what scopes this to one season: if no row
-- matches the slug, zero players are inserted rather than landing anywhere else.

INSERT INTO players (season_id, name)
SELECT season.id, incoming.name
FROM seasons AS season
CROSS JOIN (VALUES
${rows}
) AS incoming (name)
WHERE season.slug = ${q(slug)}
  AND NOT EXISTS (
    SELECT 1 FROM players existing
    WHERE existing.season_id = season.id
      AND lower(existing.name) = lower(incoming.name)
  );

-- Confirmation — expect ${roster.players.length}. A 0 here means the season does not exist yet.
SELECT count(*) AS players_in_${slug.replace(/[^a-z0-9_]/g, '_')}
FROM players p
JOIN seasons s ON s.id = p.season_id
WHERE s.slug = ${q(slug)};
`;
}

async function importToSupabase(roster) {
  const { default: dotenv } = await import('dotenv');
  dotenv.config();
  const { createClient } = await import('@supabase/supabase-js');

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    console.error(
      'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.\n' +
        'Either add them, or re-run with --sql and paste the output into the Supabase SQL Editor.'
    );
    process.exit(1);
  }
  const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });

  const slug = roster.season.slug;
  const { data: season } = await supabase.from('seasons').select('id, label').eq('slug', slug).maybeSingle();
  if (!season) {
    console.error(`Season "${slug}" does not exist — create it first.`);
    process.exit(1);
  }

  const { data: existing, error: readErr } = await supabase
    .from('players').select('name').eq('season_id', season.id);
  if (readErr) {
    console.error(`Could not read existing players: ${readErr.message}`);
    process.exit(1);
  }
  const have = new Set((existing || []).map(p => p.name.trim().toLowerCase()));

  const toInsert = roster.players
    .map(name => name.trim())
    .filter(name => !have.has(name.toLowerCase()))
    .map(name => ({ season_id: season.id, name }));

  if (toInsert.length === 0) {
    console.log(`All ${roster.players.length} players already present in ${season.label}. Nothing to do.`);
    return;
  }

  const { error } = await supabase.from('players').insert(toInsert);
  if (error) {
    console.error(`Insert failed: ${error.message}`);
    process.exit(1);
  }
  const skipped = roster.players.length - toInsert.length;
  console.log(
    `Inserted ${toInsert.length} player(s) into ${season.label}` +
    (skipped ? ` (${skipped} already present).` : '.')
  );
}

const invokedDirectly = process.argv[1] && import.meta.url.endsWith(process.argv[1].split(/[\\/]/).pop());
if (invokedDirectly) {
  const { rosterPath, sqlOnly } = parseArgs(process.argv);
  const roster = JSON.parse(readFileSync(rosterPath, 'utf8'));

  const errors = validateRoster(roster);
  if (errors.length) {
    console.error(`${rosterPath} is not valid:\n  ` + errors.join('\n  '));
    process.exit(1);
  }

  if (sqlOnly) process.stdout.write(toSql(roster));
  else await importToSupabase(roster);
}
